Update php.yml
Signed-off-by: Koissi <70168615+SaviKoissi@users.noreply.github.com>

diff --git a/.github/workflows/php.yml b/.github/workflows/php.yml
--- a/.github/workflows/php.yml
+++ b/.github/workflows/php.yml
@@ -3,7 +3,7 @@ name: Deploy Website
 on:
   push:
     branches:
-      - main  # Change this to your main branch name
+      - main
 
 jobs:
   deploy:
@@ -20,17 +20,15 @@ jobs:
     
     - name: Install dependencies
       run: npm install 
-      working-directory: HeathDataInsights.io
     
     - name: Build website
       run: npm run build
-      working-directory: HeathDataInsights.io
-    
+
     - name: Check if package.json exists
-      run: test -f HeathDataInsights.io/package.json || echo "package.json not found"
-    
+      run: test -f package.json || echo "package.json not found"
+
     - name: Deploy to GitHub Pages
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
-        publish_dir: HeathDataInsights.io/build  # Replace with the directory containing your built website
+        publish_dir: ./build  # Replace with the directory containing your built website
