Update php.yml
Signed-off-by: Koissi <70168615+SaviKoissi@users.noreply.github.com>

diff --git a/.github/workflows/php.yml b/.github/workflows/php.yml
--- a/.github/workflows/php.yml
+++ b/.github/workflows/php.yml
@@ -26,6 +26,10 @@ jobs:
       run: npm run build
       working-directory: HeathDataInsights.io 
       
+      - name: Check if package.json exists
+      run: test -f HeathDataInsights.io/package.json || echo "package.json not found"
+    
+      
     - name: Deploy to GitHub Pages
       uses: peaceiris/actions-gh-pages@v3
       with:
