Update php.yml
Signed-off-by: Koissi <70168615+SaviKoissi@users.noreply.github.com>

diff --git a/.github/workflows/php.yml b/.github/workflows/php.yml
--- a/.github/workflows/php.yml
+++ b/.github/workflows/php.yml
@@ -19,13 +19,18 @@ jobs:
         node-version: '14'
     
     - name: Install dependencies
-      run: npm install  # Replace with your build command if using a different technology
+      run: npm install 
+      working-directory: ./HeathDataInsights.io
     
     - name: Build website
-      run: npm run build  # Replace with your build command
+      run: npm run build
+      working-directory: ./HeathDataInsights.io
+      
+    - name: Check if package.json exists
+      run: test -f HeathDataInsights.io/package.json || echo "package.json not found"
     
     - name: Deploy to GitHub Pages
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
-        publish_dir: ./build  # Replace with the directory containing your built website
+        publish_dir: ./HeathDataInsights.io/build  # Replace with the directory containing your built website
